version: "2"

linters:
  default: all
  disable:
    - godoclint
    - funcorder

    #
    # Redundant
    #
    - cyclop    # revive
    - funlen    # revive
    - gocognit  # revive
    - gocyclo   # revive
    - lll       # revive

    - exhaustive            # check exhaustiveness of enum switch statements
    - godot                 # Check if comments end in a period
    - gosec                 # (gas): Inspects source code for security problems
    - inamedparam           # reports interfaces with unnamed method parameters
    - promlinter            # Check Prometheus metrics naming via promlint
    - wrapcheck             # Checks that errors returned from external packages are wrapped

    - mnd                   # An analyzer to detect magic numbers.

    - nlreturn              # nlreturn checks for a new line before return and branch statements to increase code clarity
    - whitespace            # Whitespace is a linter that checks for unnecessary newlines at the start and end of functions, if, for, etc.
    - wsl                   # add or remove empty lines
    - wsl_v5                # add or remove empty lines
    - noinlineerr
    - embeddedstructfieldcheck

    - godox                 # Tool for detection of FIXME, TODO and other comment keywords
    - err113                # Go linter to check the errors handling expressions
    - paralleltest          # Detects missing usage of t.Parallel() method in your Go test
    - testpackage           # linter that makes you use a separate _test package

    - exhaustruct           # Checks if all structure fields are initialized
    - forbidigo             # Forbids identifiers
    - gochecknoglobals      # Check that no global variables exist.
    - goconst               # Finds repeated strings that could be replaced by a constant
    - tagliatelle           # Checks the struct tags.
    - varnamelen            # checks that the length of a variable's name matches its scope
    - prealloc
    - forcetypeassert  # !!!

    - depguard
    - nonamedreturns

    - noctx   # !!!
    - perfsprint # !!!


  settings:

    errcheck:
      # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
      # Such cases aren't reported by default.
      check-type-assertions: false

    gocritic:
      enable-all: true
      disabled-checks:
        - paramTypeCombine
        - todoCommentWithoutDetail
        - emptyStringTest # !!!
        - exposedSyncMutex # !!!
        - commentedOutCode
        - unnamedResult
        - importShadow # !!!
        - commentFormatting
        - whyNoLint

    govet:
      disable:
        - fieldalignment
        - shadow # !!!
      enable-all: true

    maintidx:
      # adjusted to accommodate API constructor complexity
      under: 17

    misspell:
      locale: US

    modernize:
      disable:
        - any   # !!!
        - bloop
        - testingcontext  # !!!

    nestif:
      # lower this after refactoring
      min-complexity: 12

    nlreturn:
      block-size: 5

    nolintlint:
      require-explanation: false  # don't require an explanation for nolint directives
      require-specific: true      # require nolint directives to be specific about which linter is being skipped
      allow-unused: false         # report any unused nolint directives

    perfsprint:
      error-format: true
      string-format: true

    revive:
      severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: bool-literal-in-expr
          disabled: true   # !!!
        - name: cognitive-complexity
          arguments:
            # lower this after refactoring
            - 40
        - name: comment-spacings
          disabled: true
        - name: cyclomatic
          arguments:
            # lower this after refactoring
            - 33
        - name: enforce-switch-style
          disabled: true
        - name: context-as-argument
          disabled: true  # !!!
        - name: empty-lines
          disabled: true
        - name: function-length
          arguments:
            # lower this after refactoring
            - 93
            - 233
        - name: import-alias-naming
          disabled: true
        - name: import-shadowing
          disabled: true  # !!!
        - name: line-length-limit
          arguments:
            # lower this after refactoring
            - 231
        - name: max-control-nesting
          arguments:
            # lower this after refactoring
            - 6
        - name: if-return
          disabled: true   # !!!
        - name: package-directory-mismatch
          disabled: true  # !!!
        - name: struct-tag
          disabled: true   # !!!
        - name: var-naming
          disabled: true   # !!!
        - name: exported
          disabled: true   # !!!
        - name: indent-error-flow
          disabled: true   # !!!
        - name: unexported-naming
          disabled: true  # !!!
        - name: unnecessary-format
          disabled: true  # !!!
        - name: unused-parameter
          disabled: true   # !!!
        - name: use-any
          disabled: true   # !!!
        - name: use-errors-new
          disabled: true   # !!!
        - name: unused-receiver
          disabled: true   # !!!
        - name: var-declaration
          disabled: true   # !!!

    staticcheck:
      checks:
        - all
        - -ST1003   # !!!

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:

      # `err` is often shadowed, we may continue to do it

      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration'

      # we use t,ctx instead of ctx,t in tests
      - linters:
          - revive
        path: pkg/(.+)_test.go
        text: 'context-as-argument: context.Context should be the first parameter of a function'

    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/crowdsecurity)
        - prefix(github.com/crowdsecurity/crowdsec)

  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
