#!/bin/sh

systemctl daemon-reload

#shellcheck source=./scripts/_bouncer.sh
. "/usr/lib/$DPKG_MAINTSCRIPT_PACKAGE/_bouncer.sh"
START=1

if [ "$1" = "configure" ]; then
    if need_api_key; then
        if ! set_api_key; then
            START=0
        fi
    fi
fi

systemctl --quiet is-enabled "$SERVICE" || systemctl unmask "$SERVICE" && systemctl enable "$SERVICE"

set_local_lapi_url 'CROWDSEC_LAPI_URL'

if [ "$START" -eq 0 ]; then
    echo "no api key was generated, you can generate one on your LAPI server by running 'cscli bouncers add <bouncer_name>' and add it to '$CONFIG'" >&2
fi

if ! getent passwd crowdsec-spoa >/dev/null; then
    adduser crowdsec-spoa --system --group --comment "crowdsec haproxy spoa bouncer"
fi

echo "please enter the binary path in '$CONFIG' and start the bouncer via 'sudo systemctl start $SERVICE'"
echo "To configure your haproxy, please refer to the documentation at https://docs.crowdsec.net/docs/haproxy-bouncer/"
echo "Some configuration examples can be found in /usr/share/doc/crowdsec-haproxy-spoa-bouncer/examples/"
