#!/bin/sh

set -eu

#shellcheck source=./scripts/_bouncer.sh
. "/usr/lib/$DPKG_MAINTSCRIPT_PACKAGE/_bouncer.sh"

systemctl stop "$SERVICE" || echo "cannot stop service"
systemctl disable "$SERVICE" || echo "cannot disable service"

cmp /etc/haproxy/crowdsec.cfg /usr/share/doc/crowdsec-haproxy-spoa-bouncer/examples/crowdsec.cfg &&
    rm -f /etc/haproxy/crowdsec.cfg || echo "not removing /etc/haproxy/crowdsec.cfg, it has been modified"
